apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limits
  namespace: ecuaalejo2013-dev
spec:
  limits:
  - max:
      cpu: "2"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 128Mi
    type: pod
